export const RES_DATA = {
  statusCode: 0,
  data: {
    cacheExpiryTime: 320,
    pages: 1,
    pageIndex: 0,
    scrubber: 0,
    filters: [
      {
        type: "FilterWidget",
        title: "Cuisines",
        key: "CUISINES",
        configType: "checkbox",
        visible: 1,
        options: [
          { option: "American", selected: 0, visible: 1 },
          { option: "Bakery", selected: 0, visible: 1 },
          { option: "Beverages", selected: 0, visible: 1 },
          { option: "Biryani", selected: 0, visible: 1 },
          { option: "Burgers", selected: 0, visible: 1 },
          { option: "Cafe", selected: 0, visible: 1 },
          { option: "Chaat", selected: 0, visible: 1 },
          { option: "Chinese", selected: 0, visible: 1 },
          { option: "Continental", selected: 0, visible: 1 },
          { option: "Desserts", selected: 0, visible: 1 },
          { option: "Fast Food", selected: 0, visible: 1 },
          { option: "Grill", selected: 0, visible: 1 },
          { option: "Gujarati", selected: 0, visible: 1 },
          { option: "Healthy Food", selected: 0, visible: 1 },
          { option: "Home Food", selected: 0, visible: 1 },
          { option: "Ice Cream", selected: 0, visible: 1 },
          { option: "Ice Cream Cakes", selected: 0, visible: 1 },
          { option: "Indian", selected: 0, visible: 1 },
          { option: "Italian", selected: 0, visible: 1 },
          { option: "Italian-American", selected: 0, visible: 1 },
          { option: "Juices", selected: 0, visible: 1 },
          { option: "Kebabs", selected: 0, visible: 1 },
          { option: "Kerala", selected: 0, visible: 1 },
          { option: "Maharashtrian", selected: 0, visible: 1 },
          { option: "Mexican", selected: 0, visible: 1 },
          { option: "Middle Eastern", selected: 0, visible: 1 },
          { option: "Mughlai", selected: 0, visible: 1 },
          { option: "Navratri Special", selected: 0, visible: 1 },
          { option: "North Indian", selected: 0, visible: 1 },
          { option: "Oriya", selected: 0, visible: 1 },
          { option: "Paan", selected: 0, visible: 1 },
          { option: "Pastas", selected: 0, visible: 1 },
          { option: "Pizzas", selected: 0, visible: 1 },
          { option: "Punjabi", selected: 0, visible: 1 },
          { option: "Salads", selected: 0, visible: 1 },
          { option: "Snacks", selected: 0, visible: 1 },
          { option: "South Indian", selected: 0, visible: 1 },
          { option: "Street Food", selected: 0, visible: 1 },
          { option: "Sweets", selected: 0, visible: 1 },
          { option: "Tandoor", selected: 0, visible: 1 },
          { option: "Thai", selected: 0, visible: 1 },
          { option: "Thalis", selected: 0, visible: 1 },
          { option: "Waffle", selected: 0, visible: 1 },
        ],
        detail: "",
        heading: "Cuisines",
        applicable: 1,
        searchable: 1,
      },
      {
        type: "FilterWidget",
        title: "Show Restaurants With",
        key: "SHOW_RESTAURANTS_WITH",
        configType: "checkbox",
        visible: 1,
        options: [{ option: "Pure Veg", selected: 0, visible: 1 }],
        detail: "",
        heading: "Offers & More",
        applicable: 1,
        searchable: 0,
      },
    ],
    sorts: [
      {
        type: "SortWidget",
        key: "RELEVANCE",
        title: "Relevance",
        selected: 1,
        visible: 1,
        defaultSelection: true,
      },
      {
        type: "SortWidget",
        key: "DELIVERY_TIME",
        title: "Delivery Time",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "RATING",
        title: "Rating",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO",
        title: "Cost: Low to High",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO_H2L",
        title: "Cost: High to Low",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
    ],
    configs: {
      ribbons: {
        PREORDER: {
          type: "PREORDER",
          text: "Preorder",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 3,
        },
        EXCLUSIVE: {
          type: "EXCLUSIVE",
          text: "Exclusive",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 2,
        },
        NEW: {
          type: "NEW",
          text: "Newly Added",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 4,
        },
        REPEAT: {
          type: "REPEAT",
          text: "Repeat",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#D53D4C",
          bottomBackgroundColor: "#B02331",
          priority: 6,
        },
        CLOUD: {
          type: "CLOUD",
          text: "Daily Menus",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 5,
        },
        PREMIUM: {
          type: "PREMIUM",
          text: "Premium",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#8a584b",
          bottomBackgroundColor: "#583229",
          priority: 7,
        },
        PROMOTED: {
          type: "PROMOTED",
          text: "Promoted",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#3a3c41",
          bottomBackgroundColor: "#1e2023",
          priority: 1,
        },
      },
      croutons: {
        RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "${amount} extra levied on some restaurants",
        },
        SERVICEABLE_WITH_BANNER_RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "rain_crouton_4x",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "Few restaurants unserviceable due to rains",
        },
      },
    },
    cards: [
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "topCarousel",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 635529,
                  creativeId: "rng/md/carousel/production/pneknawbadtvceqzwiep",
                  type: "restaurantCollectionV2",
                  link: "49301",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 284091,
                  creativeId: "rng/md/carousel/production/qsgjyrelvjr3atzl0ypm",
                  type: "restaurantCollectionV2",
                  link: "46726",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607193,
                  creativeId: "rng/md/carousel/production/s5ug2key6e2sptaxku5v",
                  type: "restaurantCollectionV2",
                  link: "56410",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607195,
                  creativeId: "rng/md/carousel/production/ifi2lbzxeu1hvsqrsip3",
                  type: "restaurantCollectionV2",
                  link: "56421",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "openFilter",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181684,
                  creativeId: "bkhjfipzydkoqncrxpyi",
                  type: "restaurantCollectionV2",
                  link: "11718",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Offers Near You",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Offers Near You",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "eyperwsfhaoa5vktjtu4",
                  dwebOpenFilterDeselectIcon: "urw8usdf4mk9aywd59gq",
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181680,
                  creativeId: "a3jqjjod5taken7dh1bs",
                  type: "restaurantCollectionV2",
                  link: "11721",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Veg Only",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Vegetarian Options",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "qtjc8dzfexg72lug37a0",
                  dwebOpenFilterDeselectIcon: "bm8bziikwyvwqsml1clm",
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "seeAllRestaurants",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "seeAllRestaurants",
          data: {
            title: "SEE ALL",
            totalOpenRestaurants: 392,
            cards: [
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "73831",
                  name: "Radhe Dhokla",
                  uuid: "aeabc7cb-61b3-4dd6-87a7-81f316267fdb",
                  city: "21",
                  area: "Nanpura",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "27947ad42435b18fc7d1f127e841748a",
                  cuisines: ["Chinese", "North Indian", "Biryani"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 25,
                  minDeliveryTime: 25,
                  maxDeliveryTime: 25,
                  slaString: "25 MINS",
                  lastMileTravel: 4.199999809265137,
                  slugs: {
                    restaurant: "radhe-dhokla-athwa-athwa",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "Opposite Lalbhai Contractor Complex, Nr. Library Nanpura Main Road, Nanpura, Surat",
                  locality: "Navdi Bandar Road",
                  parentId: 4921,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [{ type: "PROMOTED" }],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 2400, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 2400,
                    message: "",
                    title: "Delivery Charge",
                    amount: "2400",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7355555~p=1~eid=00000189-33cf-d75a-0600-489c0072013f~srvts=1688791406426",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.1 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "73831",
                    deliveryTime: 25,
                    minDeliveryTime: 25,
                    maxDeliveryTime: 25,
                    lastMileTravel: 4.199999809265137,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.4",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "93694",
                  name: "New Janta Dairy",
                  uuid: "4646d5ab-5240-4794-9f7a-b525726f10da",
                  city: "21",
                  area: "Althan Bhatar",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "mstdherryaqj9wj4qkyo",
                  cuisines: ["Desserts"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 19,
                  minDeliveryTime: 19,
                  maxDeliveryTime: 19,
                  slaString: "19 MINS",
                  lastMileTravel: 0.6000000238418579,
                  slugs: {
                    restaurant: "new-janta-dairy-piplod-piplod",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "shop no 224, 1st floor, near manher dying udhna magdalla road, bhatiya complex surat",
                  locality: "Sosyo Circle",
                  parentId: 8623,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "93694",
                    deliveryTime: 19,
                    minDeliveryTime: 19,
                    maxDeliveryTime: 19,
                    lastMileTravel: 0.6000000238418579,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.2",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "321766",
                  name: "Kavya's Egg Corner",
                  uuid: "c413cce0-c5d4-43cc-ac2b-e4c41773b16a",
                  city: "21",
                  area: "Athwa",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "clcj0roto0f4nwz8szfc",
                  cuisines: [
                    "Fast Food",
                    "Mughlai",
                    "Biryani",
                    "North Indian",
                    "Punjabi",
                    "Beverages",
                  ],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 23,
                  minDeliveryTime: 23,
                  maxDeliveryTime: 23,
                  slaString: "23 MINS",
                  lastMileTravel: 1.600000023841858,
                  slugs: { restaurant: "kavya-athwa-athwa", city: "surat" },
                  cityState: "21",
                  address:
                    "Shop No-4, Ashirwad Township No.2, Bamroli Road, Surat City, Municipal Corporation, Gujarat",
                  locality: "Bamroli Road",
                  parentId: 313795,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.6 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹199",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "321766",
                    deliveryTime: 23,
                    minDeliveryTime: 23,
                    maxDeliveryTime: 23,
                    lastMileTravel: 1.600000023841858,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.9",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "503690",
                  name: "Prem Egg House",
                  uuid: "5eaae9f4-dc66-48d9-bc14-8e9ea533c733",
                  city: "21",
                  area: "Athwa",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "bt1ztqc7v7jourvwo0wt",
                  cuisines: ["Tandoor", "North Indian", "Mughlai", "Biryani"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 23,
                  minDeliveryTime: 23,
                  maxDeliveryTime: 23,
                  slaString: "23 MINS",
                  lastMileTravel: 1.600000023841858,
                  slugs: {
                    restaurant: "prem-egg-house-dindoli-dindoli",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "NEAR USHA AUTO TYRES, OPP WELL COME PAN HOUSE, BAMROLI ROAD, UDHNA, SURAT, Surat City , Surat City, Surat Municipal Corporation, Gujarat - 394210",
                  locality: "Bamroli Road",
                  parentId: 301637,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.6 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹199",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "503690",
                    deliveryTime: 23,
                    minDeliveryTime: 23,
                    maxDeliveryTime: 23,
                    lastMileTravel: 1.600000023841858,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.7",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "529855",
                  name: "Bombay Vadapav",
                  uuid: "0fab35b2-9cd7-4cad-801b-26da9bdf1227",
                  city: "21",
                  area: "Pandesara",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "bo9us1k3wwsyq66fza0n",
                  cuisines: ["Street Food", "Chaat", "Snacks"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 22,
                  minDeliveryTime: 22,
                  maxDeliveryTime: 22,
                  slaString: "22 MINS",
                  lastMileTravel: 1.600000023841858,
                  slugs: {
                    restaurant: "bombay-vada-pav-athwa-athwa",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "SHOP NO.3, ASHIRWAD TOWNSHIP NO.2, BAMROLI ROAD, SURAT",
                  locality: "Bamroli Road",
                  parentId: 48910,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "529855",
                    deliveryTime: 22,
                    minDeliveryTime: 22,
                    maxDeliveryTime: 22,
                    lastMileTravel: 1.600000023841858,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "121518",
                  name: "Maakhan Bhog",
                  uuid: "59451f9d-8929-4281-ad30-0ad9b51d2c64",
                  city: "21",
                  area: "Athwa",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "cb920fb9f77c0097fadbbc1586390a67",
                  cuisines: ["Desserts", "Chinese", "North Indian"],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 20,
                  minDeliveryTime: 20,
                  maxDeliveryTime: 20,
                  slaString: "20 MINS",
                  lastMileTravel: 3,
                  slugs: {
                    restaurant: "maakhan-bhog-ghoddod-road-athwa-athwa",
                    city: "surat",
                  },
                  cityState: "21",
                  address: "307-310, turning point complex ghoddod raod, surat",
                  locality: "Ghod Dod Road",
                  parentId: 6999,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [{ type: "PROMOTED" }],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7321883~p=19~eid=00000189-33cf-d75a-0600-48a20072134d~srvts=1688791406426",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "3 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "40% OFF",
                    subHeader: "UPTO ₹80",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "121518",
                    deliveryTime: 20,
                    minDeliveryTime: 20,
                    maxDeliveryTime: 20,
                    lastMileTravel: 3,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.2",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "683601",
                  name: "Kolkata Sweet",
                  uuid: "f85df260-9181-4685-beb9-976b3d2a4fe6",
                  city: "21",
                  area: "Athwa",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "070da0af9e4d04ee744ef3bc0b9a2902",
                  cuisines: ["Desserts"],
                  tags: [],
                  costForTwo: 28000,
                  costForTwoString: "₹280 FOR TWO",
                  deliveryTime: 20,
                  minDeliveryTime: 20,
                  maxDeliveryTime: 20,
                  slaString: "20 MINS",
                  lastMileTravel: 1.5,
                  slugs: {
                    restaurant: "kolkata-sweet-athwa-athwa",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "BLOCK NO-29,PLOT NO-10-11,SHOP NO-1, RAMDEV NAGAR,UDHANAGAM,SURAT. 394210, Surat City, Surat City, Surat Municipal Corporation, Gujarat - 394210 ",
                  locality: "Dr Hedgewar Rd",
                  parentId: 407963,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.5 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "20% OFF",
                    subHeader: "UPTO ₹50",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "683601",
                    deliveryTime: 20,
                    minDeliveryTime: 20,
                    maxDeliveryTime: 20,
                    lastMileTravel: 1.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "214074",
                  name: "Taste Of Eggs",
                  uuid: "59d5dfd8-fd21-42e6-b48a-808d49bdc0ce",
                  city: "21",
                  area: "Vesu",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "6e4620dd3d9f2fea1e1d4d70bbfd7bfe",
                  cuisines: [
                    "Street Food",
                    "Tandoor",
                    "Punjabi",
                    "North Indian",
                    "Biryani",
                  ],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 25,
                  minDeliveryTime: 25,
                  maxDeliveryTime: 25,
                  slaString: "25 MINS",
                  lastMileTravel: 1.600000023841858,
                  slugs: {
                    restaurant: "taste-of-egg-udhna-udhna",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "PLOT NO.4, ASHIRWAD TOWNSHOP 2 BAMROLI ROAD, UDHNA, Pandesara,Surat city,Surat Municipal corporation,Gujrat-394210",
                  locality: "Bamroli Road",
                  parentId: 201571,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.6 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹199",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "214074",
                    deliveryTime: 25,
                    minDeliveryTime: 25,
                    maxDeliveryTime: 25,
                    lastMileTravel: 1.600000023841858,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.8",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "481881",
                  name: "Monginis Cake Shop",
                  uuid: "7da96016-44ab-4039-a9a3-f6051d4c7b1f",
                  city: "21",
                  area: "Udhana",
                  totalRatingsString: "20+ ratings",
                  cloudinaryImageId: "dullsdj9z5xorz8zbcyx",
                  cuisines: ["Bakery", "Desserts"],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 22,
                  minDeliveryTime: 22,
                  maxDeliveryTime: 22,
                  slaString: "22 MINS",
                  lastMileTravel: 1.600000023841858,
                  slugs: {
                    restaurant: "monginis-athwa-athwa-3",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "WARD NO-27/E, SHOP NO-11, LOWER GR FLOOR, SHANTI CORNER, KASHI NAGAR SOC.,BAMROLI ROAD, UDHNA, Surat City, Surat",
                  locality: "Bamroli Road",
                  parentId: 8190,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.6 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹599",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "481881",
                    deliveryTime: 22,
                    minDeliveryTime: 22,
                    maxDeliveryTime: 22,
                    lastMileTravel: 1.600000023841858,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.2",
                  totalRatings: 20,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "133179",
                  name: "Ajay's",
                  uuid: "838f60b8-fe6e-4237-b311-f3af4471945f",
                  city: "21",
                  area: "Udhna Gam",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "bjt2cvc5afuyhj0shzjh",
                  cuisines: ["Burgers"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 18,
                  minDeliveryTime: 18,
                  maxDeliveryTime: 18,
                  slaString: "18 MINS",
                  lastMileTravel: 2,
                  slugs: {
                    restaurant: "ajays-udhna-parvat-patiya",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "Bus Depot, Gurunagar, Udhana Main Rd, beside Bharat General Store, opp. Udhana, Udhna, Surat, Gujarat 394210",
                  locality: "Udhna Teen Rasta",
                  parentId: 6439,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "133179",
                    deliveryTime: 18,
                    minDeliveryTime: 18,
                    maxDeliveryTime: 18,
                    lastMileTravel: 2,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.9",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "420617",
                  name: "24 Carats Mithai Magic",
                  uuid: "6dec6db1-61f3-40c6-ae21-b295e0f33912",
                  city: "21",
                  area: "Gopipura",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "ixiljayesjl4exxnaciy",
                  cuisines: ["Desserts", "Ice Cream"],
                  tags: [],
                  costForTwo: 50000,
                  costForTwoString: "₹500 FOR TWO",
                  deliveryTime: 22,
                  minDeliveryTime: 22,
                  maxDeliveryTime: 22,
                  slaString: "22 MINS",
                  lastMileTravel: 4.099999904632568,
                  slugs: {
                    restaurant: "24-carats-mithai-magic-athwa-athwa",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "9/1748, CHAUTA BAZAR,, Surat Municipal  Corporation, Gujarat-395003",
                  locality: "Chauta Bazaar",
                  parentId: 233994,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [{ type: "PROMOTED" }],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 2400, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 2400,
                    message: "",
                    title: "Delivery Charge",
                    amount: "2400",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7268873~p=16~eid=00000189-33cf-d75a-0600-48a10072100b~srvts=1688791406426",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹199",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "420617",
                    deliveryTime: 22,
                    minDeliveryTime: 22,
                    maxDeliveryTime: 22,
                    lastMileTravel: 4.099999904632568,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.6",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "720251",
                  name: "Egg@99",
                  uuid: "862811b7-e0ea-4a1f-baf1-7e561851edab",
                  city: "21",
                  area: "Athwa",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "5e4d53cf80cd4a92e2ec616a4bfd515e",
                  cuisines: ["North Indian"],
                  tags: [],
                  costForTwo: 19800,
                  costForTwoString: "₹198 FOR TWO",
                  deliveryTime: 23,
                  minDeliveryTime: 23,
                  maxDeliveryTime: 23,
                  slaString: "23 MINS",
                  lastMileTravel: 1.600000023841858,
                  slugs: { restaurant: "egg@99-athwa-athwa", city: "surat" },
                  cityState: "21",
                  address:
                    "OPP. USHA AUTO TYRES,ASHIRWAD TOWNSHIP -2,BAMROLI ROAD,UDHNA,SURAT, Surat-394210",
                  locality: "Bamroli Road",
                  parentId: 429211,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "720251",
                    deliveryTime: 23,
                    minDeliveryTime: 23,
                    maxDeliveryTime: 23,
                    lastMileTravel: 1.600000023841858,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: true,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "670670",
                  name: "Siddhi Vadapav And Samosa\t",
                  uuid: "9c914b4b-8a7f-4d16-bc62-98052f2c32dd",
                  city: "21",
                  area: "Athwa",
                  totalRatingsString: "20+ ratings",
                  cloudinaryImageId: "3f52aec9fb1cf0a622855c14657c26a4",
                  cuisines: ["Indian", "Snacks"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 21,
                  minDeliveryTime: 21,
                  maxDeliveryTime: 21,
                  slaString: "21 MINS",
                  lastMileTravel: 1.7000000476837158,
                  slugs: {
                    restaurant: "siddhi-vadapav-and-samosa-athwa-athwa",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "5R9C+7M3, beside shreenath bhojnalay, Gandhi Kutir, Surat, Gujarat 395017, India",
                  locality: "shreenath bhojnalay",
                  parentId: 401994,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.7 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "40% OFF",
                    subHeader: "UPTO ₹80",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "670670",
                    deliveryTime: 21,
                    minDeliveryTime: 21,
                    maxDeliveryTime: 21,
                    lastMileTravel: 1.7000000476837158,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.8",
                  totalRatings: 20,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "170067",
                  name: "Agra Sweets And Namkeen",
                  uuid: "0f814e3d-d10e-42e0-aae7-9f9c5276c8ec",
                  city: "21",
                  area: "Athwa",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "zps9evy49kqel9miogpw",
                  cuisines: ["Desserts", "North Indian", "South Indian"],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 15,
                  minDeliveryTime: 15,
                  maxDeliveryTime: 15,
                  slaString: "15 MINS",
                  lastMileTravel: 2.200000047683716,
                  slugs: {
                    restaurant: "agra-sweets-and-namkeen-athwa",
                    city: "surat",
                  },
                  cityState: "21",
                  address:
                    "shop no 8 , Mangaldip Appartment, Bhatar Road, Surat",
                  locality: "Bhatar Road",
                  parentId: 27806,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2.2 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "170067",
                    deliveryTime: 15,
                    minDeliveryTime: 15,
                    maxDeliveryTime: 15,
                    lastMileTravel: 2.200000047683716,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.6",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "408231",
                  name: "Shree Tirupati Balaji Idli",
                  uuid: "041c990c-481c-4433-b47f-c9fd75d7691c",
                  city: "21",
                  area: "Althan Bhatar",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "nicowsp9pufgiwxyhhsr",
                  cuisines: ["South Indian"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 17,
                  minDeliveryTime: 17,
                  maxDeliveryTime: 17,
                  slaString: "17 MINS",
                  lastMileTravel: 2.9000000953674316,
                  slugs: {
                    restaurant: "shree-tirupati-balaji-idli-athwa-athwa",
                    city: "surat",
                  },
                  cityState: "21",
                  address: "Near umabhavan, Bhatar road surat - 395001",
                  locality: "Bhatar Char Rasta",
                  parentId: 255248,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 1900, message: "" },
                      { name: "time", fee: 0, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2.9 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "408231",
                    deliveryTime: 17,
                    minDeliveryTime: 17,
                    maxDeliveryTime: 17,
                    lastMileTravel: 2.9000000953674316,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.3",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
            ],
            totalRestaurants: 392,
          },
          subtype: "personalized",
        },
        parentWidget: false,
      },
    ],
    nextPageFetch: 0,
  },
  tid: "b51fb96a-dd23-4c7b-ab69-61ea1bf81908",
  sid: "82a337f7-99f7-4fd6-9ac3-14970c1a9df5",
  deviceId: "4bf99d8d-9a95-8eed-536d-5ebe80a61a0a",
  csrfToken: null,
};
